export const Images = {
    home: require('./icons/home.png'),
    cart:require('./icons/cart.png'),
    categories:require('./icons/categories.png'),
    myprofile:require('./icons/myprofile.png'),
    phone: require('./icons/phone.png'),
    imgone:require('./icons/imgone.png'),
    imgtow:require('./icons/imgtow.png'),
    imgthree:require('./icons/imgthree.png'),
    imgfour:require('./icons/imgfour.png'),
    imgfive:require('./icons/imgfive.png'),
    productOne:require('./icons/productOne.png'),
    productTow:require('./icons/productTow.png'),
    productThree:require('./icons/productThree.png'),
    cart_photo: require('../Images/cart_photo.png'),
    dustbin: require('../Images/Dustbin.png'),
    profile:require('../Images/Profile2.png'),
    WishList: require('./icons/Like.png'),
    History: require('./icons/history.png'),
    order: require('./icons/order.png'),
    setting: require('./icons/Setting.png'),
    feedback: require('./icons/Feedback.png'),
    LogOut: require('./icons/LogOut.png'),
    filter: require('./icons/filter.png'),
};