export const NavigationRoutes = {
  welcom: 'Welcom',
  home: 'Home',
  categories: 'Categories',
  cart: 'Cart',
  my_profile: 'My Profil',
  bottom: 'BootamTabNavigation',
  login: 'Login',
  signup: 'Signup',
  notification: 'Notification',
  Search: 'Search',
  Category: 'Category',
  wishlist:'Wishlist',
  ProductDetail: 'ProductDetail',
  profile:'MyProfile',
  settings: 'Settings',
  myorders:'MyOrders',
  trackandvieworder:'TrackAndViewOrder',
};
