export const NavigationRoutes = {
  welcom: 'Welcom',
  home: 'Homes',
  categories: 'Categories',
  cart: 'Cart',
  my_profile: 'My Profil',
  bottom: 'BootamTabNavigation',
  login: 'Login',
  signup: 'Signup',
  notification: 'Notification',
  Search: 'Search',
  Category: 'Category',
  ProductDetail: 'ProductDetail',
  wishlist: 'Wishlist',
  profile: 'MyProfile',
  settings: 'Settings',
  myorders: 'MyOrders',
  trackandvieworder: 'TrackAndViewOrder',
  DeliveryStep1: 'DeliveryStep1',
  DeliveryStep2: 'DeliveryStep2',
  PaymentMethod: 'PaymentMethod',
  PaymentSuccess: 'PaymentSuccess',
  OtpOne: 'OtpOne',
  OtpTow: 'OtpTow',
  HomeStake: 'Home'
};
