export const Strings = {
  password: 'Password',
  email: 'Email',
  enterEmail: 'Enter your email',
  enterPassword: 'Enter your password',
  firstname: 'First Name',
  enterfirst: 'Enter your first name',
  lastname: 'Last Name',
  enterlast: 'Enter your last name',
  mobile: 'Mobile Number',
  enternumber: 'Enter your mobile number',
  enterpassword: 'Enter Password',
  confirmpass: 'Confirm Password',
  enterconfirm: 'Retype your Password',
  App_Logo: 'App Logo',
  Lets_Get_Started: 'Let’s Get Started',
  All_Categories: 'All Categories',
  Your_Cart: 'Your Cart',
  Price_Details: 'Price Details',
  Price: 'Price (2 items)',
  Discount: 'Discount',
  Delivery_Charges: 'Delivery Charges',
  Free_Delivery: 'Free Delivery',
  Total_Amount: 'Total Amount',
  Place_Order: 'Place Order',
  Profile: 'Profile',
  Wishlist: 'Wishlist',
  Invoice_History: 'Invoice History',
  My_Orders: 'My Orders',
  Settings: 'Settings',
  Feedback: 'Feedback',
  Log_Out: 'Log Out',
  SearchResults: 'Search Results',
  TotalProductAvailable: 'Total 28 Products Available',
  Filters: 'Filters',
  EYEBOGLER:'EYEBOGLER Men Regular Fit Hoodie',
  Men_Regular_Fit_Hoodie: 'Men Regular Fit Hoodie',
  Coupon:'Coupon :',
  offer_price:'Offer Price ₹308',
  offer_detail:'Get Flat Rs 300 Off on cart value of 990 & Above.',
  Offers:'+17 Coupon offers',
  BankOffer:'Bank Offer :',
  BankOfferDetail:'Get Upto Rs. 500 Cashback of Rs. 1000',
  Bank_Offer:'+6 Bank offers',
  Color:'Color'
};
