export const Strings = {
  password: 'Password',
  email: 'Email',
  enterEmail: 'Enter your email',
  enterPassword: 'Enter your password',
  firstname: 'First Name',
  enterfirst: 'Enter your first name',
  lastname: 'Last Name',
  enterlast: 'Enter your last name',
  mobile: 'Mobile Number',
  enternumber: 'Enter your mobile number',
  enterpassword: 'Enter Password',
  confirmpass: 'Confirm Password',
  enterconfirm: 'Retype your Password',
  App_Logo: 'App Logo',
  Lets_Get_Started: 'Let’s Get Started',
  All_Categories: 'All Categories',
  Your_Cart: 'Your Cart',
  Price_Details: 'Price Details',
  Price: 'Price (2 items)',
  Discount: 'Discount',
  Delivery_Charges: 'Delivery Charges',
  Free_Delivery: 'Free Delivery',
  Total_Amount: 'Total Amount',
  Place_Order: 'Place Order',
  Profile: 'Profile',
  Wishlist: 'Wishlist',
  Invoice_History: 'Invoice History',
  My_Orders: 'My Orders',
  Settings: 'Settings',
  Feedback: 'Feedback',
  Log_Out: 'Log Out',
  SearchResults: 'Search Results',
  TotalProductAvailable: 'Total 28 Products Available',
  Filters: 'Filters',
  EYEBOGLER: 'EYEBOGLER Men Regular Fit Hoodie',
  Men_Regular_Fit_Hoodie: 'Men Regular Fit Hoodie',
  Coupon: 'Coupon :',
  offer_price: 'Offer Price ₹308',
  offer_detail: 'Get Flat Rs 300 Off on cart value of 990 & Above.',
  Offers: '+17 Coupon offers',
  BankOffer: 'Bank Offer :',
  BankOfferDetail: 'Get Upto Rs. 500 Cashback of Rs. 1000',
  Bank_Offer: '+6 Bank offers',
  Color: 'Color',
  Select_Size: 'Select Size',
  Product_Details: 'Product Details',
  List_Item1: '• We recommend you buy a size larger',
  List_Item2: '• Regular fit',
  List_Item3: '• Package contains: 1 sweatshirt',
  List_Item4: '• Machine wash',
  List_Item5: '• Cotton',
  Happy_Customer: '35 Million+    Happy Customers',
  Genuine_Product: 'Genuine Product',
  Quality_Checked: 'Quality Checked',
  Ratings:'1.2K Ratings',
  View_More: 'View More',
  Customer_Words: 'Customer Words',
  size:'Size and fit',
  Perfect:'Perfect',
  Product_Quality:'Product Quality',
  Average:'Average ',
  free_Deliver:'Free delivery',
  Apply_Coupon: 'Apply Coupon',
  shoes:'Badminton Shoes For Men',
  return:'10 days Return and Exchange',
  Order_Details: 'Order Details',
  Bag_total: 'Bag total',
  Bag_Savings: 'Bag Savings',
  Convenience_Fee: 'Convenience Fee',
  What_this: 'What’s this?',
  Delivery_Fee: 'Delivery Fee',
  Platform_Fee: 'Platform Fee',
  refund:'Return/Refund policy',
  refund_policy:'In case or return, we ensure quick refunds. Full amount will be refunded excluding Convenience',
  Read_policy: 'Read policy',
  Delivery_Details: 'Delivery Details',
  name: 'Johar Parker',
  location: 'Ahmedabad, Gujarat',
  pinCode: 'India - 382440',
  phone: 'Phone - 9722358740',
  deliveryType:'Cash on delivery available',
  View_Details:'View Details',
  payment:'Proceed To Payment'
};
